# Meeting Schedule and Communication

The Steering Committee meets virtually on the second Tuesday of each month at 3:30 PM Eastern Time. Meeting invitations, agendas, and [notes](https://nmfs-ost.github.io/workflows-guidebook/content/steering_committee/what.html#meeting-notes), and any other important materials are sent out in advance to all committee members. Meetings are based on need, so it is not uncommon during the development process when no feedback is needed to cancel the meeting.

During meetings, Steering Committee members are encouraged to use the raise hand feature to contribute to the discussion or utilize other Google meets features like reactions (i.e., thumbs up) or chat to add their input.

Communication with the Steering Committee is made through email, [Google chat space](https://chat.google.com/room/AAAAaTb4jQc?cls=7) and GitHub discussions for [{asar}](https://github.com/nmfs-ost/asar/discussions) and [{stockplotr}](https://github.com/nmfs-ost/stockplotr/discussions).

# Meeting Planning

Meeting topics and agenda are planned up to one week in advance by the Workflows Team. The topics are contingent on need and any topics that might have come up throughout the month before the meeting.

Occasionally, a request to discuss a topic from an outside party may arise and, when relevant, it will be added to the agenda.

Steering committee members are encouraged to preview the agenda or add their own topics when the need arises.

# Feedback Deadlines

When review or feedback is requested on the project for the Steering Committee, a 2--4 week deadline is typically given to provide ample time for review and consideration.

# Annual Meeting

Each year, we will hold a meeting to review:

1.  Steering Committee [membership](https://nmfs-ost.github.io/workflows-guidebook/content/steering_committee/who.html#sec-membership). We will ask if anyone is interested in stepping down from the committee and ideas for a suitable replacement.
2.  This guidebook. We will ask the Steering Committee to review the guidebook prior to the meeting and be prepared to offer feedback on topics that should be added, edited, removed, etc.

# Important Links

-   [{asar} repo](https://github.com/nmfs-ost/asar)
-   [{stockplotr} repo](https://github.com/nmfs-ost/stockplotr)
-   [Workflows Team GitHub](https://github.com/orgs/nmfs-ost/teams/asar-collaborators)
-   [Google chat space](https://chat.google.com/room/AAAAaTb4jQc?cls=7)
-   GitHub discussions (for [{asar}](https://github.com/nmfs-ost/asar/discussions) and [{stockplotr}](https://github.com/nmfs-ost/stockplotr/discussions)) for public and open discussion on releases, questions, and specific topics
